name: Build App windows

on:
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

jobs:
  buildForWindowsBasedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    # あなたのPCを「Runner」として登録している場合に動作します
    runs-on: [ self-hosted, Windows ]
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
        buildMethod:
          - BuildApp.Build
        unityPath:
          # あなたのPCに入っているUnity 6のパスに合わせました
          - '"C:\Program Files\Unity\Hub\Editor\6000.3.1f1\Editor\Unity.exe"'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          clean: false
          submodules: recursive

      - name: Run Build
        run: |
          ${{ matrix.unityPath }} -batchmode -quit -projectPath . -buildTarget ${{ matrix.targetPlatform }} -executeMethod ${{ matrix.buildMethod }} -logFile -

      - name: Upload App
        # 最新のv4に変更
        uses: actions/upload-artifact@v4
        with:
          name: App_Develop
          path: Builds/App/
          retention-days: 7
