name: Unity License Activation 🔑

on: workflow_dispatch

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Request manual activation file
        # バージョン固定をやめ、現在のGameCI標準の「action」を直接実行する形式
        uses: game-ci/unity-request-activation-file@v4
        with:
          unityVersion: 2022.3.10f1 # あなたのUnityバージョンに合わせて適当でOKです
        id: get_alf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_License_File
          path: ${{ steps.get_alf.outputs.filePath }}
